# Site Info
title: Kangyeol-Kim Archive
# tagline: 'for textmining'
description: 'Archive for everyone'
url: http://kangyeol-kim.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Kangyeol-Kim
  description:
  #gravatar: 0a638fc7996869b1b67fb90ccf77dcfe # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/kang-yeol-kim-251857138/
    github:    https://github.com/Kangyeol-Kim
    #facebook:  https://www.facebook.com/gichanglee.84
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:kkyy10000@likelion.org

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://kangyeol-kim.github.io/public/img/picture.JPG
  caption: Original Artwork &copy; Rene Magritte, Ceci n'est pas une pipe, 1928

# Puglins
mathjax: true # whether support mathjax
#google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
disqus_short_name: 'https-kangyeol-kim-github-io' # leave blank if you don't want disqus
